server/routes/viewPatientSearch/patientSearch.test.ts, server/routes/viewPatientSearch/patientSearchValidation.test.ts, server/routes/viewPatientSearch/patientSearchValidation.ts, server/views/partials/patientSearchForm.njk
=> NN-3522: update content for search restricted patient

integration_tests/integration/removeRestrictedPatient.spec.js, integration_tests/mockApis/restrictedPatientApi.js, integration_tests/pages/removeRestrictedPatient/removeRestrictedPatientConfirmation.page.js, integration_tests/plugins/index.js, server/data/prisonApiClient.test.ts, server/data/restClient.ts, server/data/restrictedPatientApiClient.test.ts, server/data/restrictedPatientApiClient.ts, server/data/restrictedPatientResult.ts, server/data/restrictedPatientSearchClient.ts, server/routes/index.ts, server/routes/removeRestrictedPatientConfirmation/index.ts, server/routes/removeRestrictedPatientConfirmation/removeRestrictedPatientConfirmation.test.ts, server/routes/removeRestrictedPatientConfirmation/removeRestrictedPatientConfirmation.ts, server/routes/restrictedPatientSelect/restrictedPatientSelect.test.ts, server/routes/restrictedPatientSelect/restrictedPatientSelect.ts, server/routes/testutils/appSetup.ts, server/routes/viewPatients/viewPatients.test.ts, server/services/index.ts, server/services/removeRestrictedPatientService.test.ts, server/services/removeRestrictedPatientService.ts, server/services/restrictedPatientSearchService.test.ts, server/services/restrictedPatientSearchService.ts, server/views/pages/removeRestrictedPatient/removeRestrictedPatientConfirmation.njk, server/views/pages/restrictedPatientSelect.njk
=> NN-3524 Confirm removal of restricted patient selection page

integration_tests/integration/removeRestrictedPatient.spec.js, integration_tests/pages/removeRestrictedPatient/removeRestrictedPatientCompleted.page.js, server/routes/index.ts, server/routes/removeRestrictedPatientCompleted/index.ts, server/routes/removeRestrictedPatientCompleted/removeRestrictedPatientCompleted.test.ts, server/routes/removeRestrictedPatientCompleted/removeRestrictedPatientCompleted.ts, server/views/pages/removeRestrictedPatient/removeRestrictedPatientCompleted.njk
=> NN-3525 Removal of restricted patient completed page

integration_tests/integration/movePrisoner.spec.js, integration_tests/pages/error.page.js, server/errorHandler.test.ts, server/errorHandler.ts, server/views/pages/error.njk
For prod it looks like this:
The page has support for stack traces when in development:
=> NN-3587: psh-like Sorry page for errors

server/views/pages/removeRestrictedPatient/removeRestrictedPatientConfirmation.njk
=> NN-3632 Layout updates to remove patient confirmation page

assets/sass/application.sass, assets/sass/components/_feedback-banner.scss, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, integration_tests/integration/homepage/homepage.spec.js, integration_tests/integration/movePrisoner.spec.js, integration_tests/integration/removeRestrictedPatient.spec.js, integration_tests/integration/viewRestrictedPatients.spec.js, integration_tests/pages/homepage.js, integration_tests/pages/movePrisoner/movePrisonerSearch.page.js, integration_tests/pages/removeRestrictedPatient/removeRestrictedPatientSearch.page.js, integration_tests/pages/viewRestrictedPatients/restrictedPatientSearch.page.js, server/app.ts, server/config.ts, server/middleware/setUpWebSecurity.ts, server/utils/nunjucksSetup.ts, server/views/pages/homepage.njk, server/views/partials/feedbackBanner.njk, server/views/partials/footer.njk, server/views/partials/layout.njk
- Feedback banner
- Links in footer
=> NN-3560 Add feedback banner and links to footer

server/routes/prisonerSelect/prisonerSelect.test.ts, server/routes/prisonerSelect/prisonerSelect.ts
Reverts ministryofjustice/hmpps-restricted-patients#46
=> Revert "NN-3644 fix alerts"

server/common/alertFlagValues.ts, server/data/prisonerResult.ts, server/data/prisonerSearchResult.ts, server/routes/prisonerSelect/prisonerSelect.ts, server/services/prisonerSearchService.test.ts, server/services/prisonerSearchService.ts
- Encapsulate alert functionality
- Add in the correct filtering logic
=> NN-3644 fix bug and improve alert code

helm_deploy/values-dev.yaml
Reverts ministryofjustice/hmpps-restricted-patients#49
=> Revert "NN-3594: Allow access to dev app without VPN"

README.md
I am going to revert this every time so i can keep doing deployments until we sort these damn certificates out
=> NN-3594: Dummy change to invoke redeploy

helm_deploy/values-dev.yaml
Reverts ministryofjustice/hmpps-restricted-patients#50
=> Revert "Revert "NN-3594: Allow access to dev app without VPN""

package.json, server/data/restrictedPatientApiClient.ts, server/services/movePrisonerService.test.ts, server/services/movePrisonerService.ts
datetime is being removed from the front end and will be handled on the server.
=> NN-4087 datetime will now be handled on the server

integration_tests/integration/removeRestrictedPatient.cy.js, integration_tests/integration/viewRestrictedPatients.cy.js, server/routes/homepage/homepage.ts, server/routes/index.ts, server/routes/restrictedPatientSearch/restrictedPatientSearch.test.ts, server/routes/restrictedPatientSearch/restrictedPatientSearch.ts, server/routes/viewPatients/index.ts, server/routes/viewPatients/viewPatients.test.ts, server/routes/viewPatients/viewPatients.ts
- SDI-367: ♻️  Prefix move to hospital paths
- SDI-367: ♻️  Revert change to test that should not have been affected
- SDI-367: ♻️  Prefix view restricted patient paths
=> SDI-367: ♻️  Prefix view restricted patient paths

server/routes/movePrisoner/index.ts, server/routes/movePrisoner/movePrisoner.test.ts, server/routes/movePrisoner/movePrisoner.ts, server/routes/movePrisoner/movePrisonerCompleted.test.ts, server/routes/movePrisoner/movePrisonerCompleted.ts, server/routes/movePrisoner/movePrisonerConfirmation.test.ts, server/routes/movePrisoner/movePrisonerConfirmation.ts, server/routes/movePrisoner/prisonerSelect.test.ts, server/views/pages/prisonerSelect.njk
- SDI-367: ♻️  Switch to using query params
- SDI-367: ♻️  Switch to using query params for move prisoner
=> SDI-367: ♻️  Switch to using query params for move prisoner

integration_tests/integration/viewRestrictedPatients.cy.js, server/routes/searchPatients/restrictedPatientSearch.test.ts, server/routes/viewPatients/index.ts, server/routes/viewPatients/viewPatients.test.ts
- SDI-367: 🔒️ Add security to remove from restricted patients endpoints
- SDI-367: 🔒️ Add security to view restricted patients endpoints
=> SDI-367: 🔒️ Add security to view restricted patients endpoints

server/routes/addPatient/hospitalSelect.test.ts, server/routes/addPatient/hospitalSelect.ts, server/routes/addPatient/index.ts, server/routes/index.ts, server/routes/movePrisoner/hospitalSelect.test.ts, server/routes/movePrisoner/hospitalSelect.ts, server/routes/movePrisoner/index.ts, server/routes/movePrisoner/movePrisonerCompleted.test.ts, server/routes/movePrisoner/movePrisonerCompleted.ts, server/routes/movePrisoner/movePrisonerConfirmation.test.ts, server/routes/movePrisoner/movePrisonerConfirmation.ts, server/routes/selectHospital/hospitalSelect.ts, server/routes/testutils/appSetup.ts, server/services/hospitalSearchService.test.ts, server/services/hospitalSearchService.ts, server/services/index.ts, server/services/movePrisonerService.test.ts, server/services/movePrisonerService.ts
The `MovePrisonerService` had methods in it to get the hospital(s).  This PR splits out those methods into a new `HospitalSearchService`.
=> SDI-345: ♻️  Create select hospital service

server/routes/help/content/issuesHelp.ts
Following feedback from testing.
=> SDI-364 Help content updates

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, server/config.ts, server/middleware/setUpWebSecurity.ts
To enable prisoner search to be submitted from the global header
=> add dps to form-action csp directive

Dockerfile, integration_tests/e2e/addRestrictedPatient.cy.ts, integration_tests/e2e/frontendComponentsFallback.cy.ts, integration_tests/e2e/homepage.cy.ts, integration_tests/e2e/movePrisoner.cy.ts, integration_tests/e2e/removeRestrictedPatient.cy.ts, integration_tests/e2e/signIn.cy.ts, integration_tests/e2e/viewRestrictedPatients.cy.ts, integration_tests/mockApis/auth.ts, server/@types/express/index.d.ts, server/interfaces/hmppsUser.ts, server/middleware/setUpAuthentication.ts, server/routes/testutils/appSetup.ts
- **Update all non major NPM dependencies (#342)**
- **Update dependency applicationinsights to v3 (#344)**
- **Update dependency eslint-plugin-cypress to v3 (#345)**
- **Update dependency superagent to v9 (#346)**
- **Update dependency supertest to v7 (#347)**
- **Update Helm release generic-service to 3.2 (#348)**
- **Update Helm release generic-prometheus-alerts to 1.5 (#349)**
- **SDIT-1682: ⬆️ Upgrade node and helm charts (#350)**
- **Revert appinsights change (#353)**
- **Update all non major NPM dependencies (#355)**
- **Update Helm release generic-prometheus-alerts to 1.6 (#351)**
- **Using the user token to get user details (#352)**
- **Update all non major NPM dependencies (#356)**
- **Update Node.js to v20.13.1 (#357)**
- **Update Helm release generic-prometheus-alerts to 1.7 …
=> pgp SDIT 1802 template typescript

server/data/prisonApiClient.ts, server/routes/addPatient/addPatientCompleted.test.ts, server/routes/addPatient/addPatientConfirmation.test.ts, server/routes/addPatient/hospitalSelect.test.ts, server/routes/movePrisoner/hospitalSelect.test.ts, server/routes/movePrisoner/movePrisonerCompleted.test.ts, server/routes/movePrisoner/movePrisonerConfirmation.test.ts, server/services/agencySearchService.test.ts, server/services/agencySearchService.ts, server/services/restrictedPatientSearchService.test.ts, server/services/restrictedPatientSearchService.ts
**SDIT-2010: ♻️ Rename prison to agency as returning hospitals too**
=>  SDIT-2010: ♻️ Rename prison to agency as returning hospitals too
